apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.misc.aspnetSecretsClaim | quote }}
spec:
  storageClassName: microk8s-hostpath
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi