{{- if .Values.backup.mongodb.enabled }} 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mongodump
spec:
  storageClassName: microk8s-hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodump
spec:
  schedule: {{ .Values.backup.mongodb.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: mongodump
            persistentVolumeClaim:
              claimName: mongodump
          restartPolicy: Never
          containers:
            - name: mongodb
              image: mongo
              command : ["/bin/sh", "-c"]
              args: ["mongodump --uri \"mongodb://dbuser:qE6dP3mK1jX4rB5aH4cY6uP7lF3vV8pN@mongodb.mongodb.svc.cluster.local/?authSource=orgmanager\" -o /usr/share/mongodump/$(date +\"%d%m%H\")"]
              volumeMounts:
              - mountPath: "/usr/share/mongodump/"
                name: mongodump
{{- end }}