{{- if .Values.backup.mongodb.enabled }} 
apiVersion: v1
kind: Namespace
metadata: 
  name: backup
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodump
  namespace: backup
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodump
  namespace: backup
spec:
  schedule: {{ .Values.backup.mongodb.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: mongodump
            persistentVolumeClaim:
              claimName: mongodump
          restartPolicy: Never
          containers:
            - name: mongodb
              image: mongo
              command : ["/bin/sh", "-c"]
              args: ["mongodump --uri $MONGOURL -o /usr/share/mongodump/$(date +\"%Y.%d%m.%H%M\")"]
              volumeMounts:
              - mountPath: "/usr/share/mongodump/"
                name: mongodump
              env:
              - name: MONGOURL
                valueFrom:
                  secretKeyRef:
                    name: orgmanager-secrets
                    key: mongoUrl
{{- end }}