apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "aspnet-keys"
spec:
  storageClassName: microk8s-hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: orgmanager
          image: cr.yandex/crpj49o8ldonf3nnjpbo/orgmanager:{{ .Values.tag }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "4G"
              cpu: "1"
          ports:
            - containerPort: 5500
          volumeMounts:
              - mountPath: "/root/.aspnet/DataProtection-Keys/"
                name: "aspnet-keys"
          env:
            - name: RAND
              value: {{ randAlphaNum 20 | upper }}
            - name: OM_MONGO
              value: {{ .Values.options.mongoUrl | quote}}
            - name: OM_MONGO_DB
              value: {{ .Values.options.mongoDb | quote}}
            - name: OM_CONFIG
              value: {{ .Values.options.config }} 
            - name: OM_HOST
              value: https://{{ .Values.options.url }}
{{- if .Values.saml }}              
            - name: OM_SAML_LOGIN
              value: {{ .Values.saml.loginUrl }}
            - name: OM_SAML_CERT
              value: {{ .Values.saml.certificate | quote }}
            - name: OM_SAML_ENTITYID
              value: {{ .Values.saml.entityId }}
{{- end }}
{{- if .Values.smtp.enabled }}              
            - name: OM_SMTP_MAILFROM
              value: {{ .Values.smtp.mailFrom | quote }}
            - name: OM_SMTP_SERVER
              value: {{ .Values.smtp.server | quote }}
            - name: OM_SMTP_PORT
              value: {{ .Values.smtp.port | quote }}
            - name: OM_SMTP_SSL_ENCRYPT
              value: {{ .Values.smtp.ssl | quote }}
            - name: OM_STMP_ALLOWED_DOMAINS
              value: {{ .Values.smtp.domains | quote }}
{{- if .Values.smtp.sendToRecipient }}  
            - name: OM_EMAIL_MODE
              value: "Recipient"
{{- end }}    
{{- end }}
            - name: OM_LOG_ELASTIC
              value: "http://elasticsearch-logging.kube-system.svc.cluster.local:9200"
            - name: OM_IMPORT_MUTATE
              value: {{ .Values.options.mutateData | quote }}
{{- if .Values.options.debugEnabled }}
            - name: OM_DEBUG
              value: "true"
{{- end }}
{{- if .Values.sentry.enabled }}
            - name: OM_USE_SENTRY
              value: "true"
{{- if .Values.sentry.env }}
            - name: SENTRY_ENVIRONMENT
              value: {{ .Values.sentry.env | quote }}
{{- end }}
{{- end}}