apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: orgmanager-secrets
                  key: mongoUrl
            - name: ME_CONFIG_MONGODB_AUTH_DATABASE
              value: {{ .Values.options.mongoDb | quote }}
            - name: ME_CONFIG_SITE_BASEURL
              value: /util/mongodb/
            - name: ME_CONFIG_BASICAUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: orgmanager-secrets
                  key: mongoExpressUserName
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orgmanager-secrets
                  key: mongoExpressPassword
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: 'false'
            - name: ME_CONFIG_REQUEST_SIZE
              value: '100mb'
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  labels:
    app: mongo-express
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: mongo-express