apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_AUTH_DATABASE
              value: orgmanager
            - name: ME_CONFIG_MONGODB_AUTH_USERNAME
              value: dbuser
            - name: ME_CONFIG_MONGODB_AUTH_PASSWORD
              value: qE6dP3mK1jX4rB5aH4cY6uP7lF3vV8pN
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongodb.mongodb.svc.cluster.local
            - name: ME_CONFIG_SITE_BASEURL
              value: /util/mongodb/
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: admin15
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: qE6dP3mK1jX4rB5aH4cY6uP7lF3vV8pN
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: 'false'
            - name: ME_CONFIG_REQUEST_SIZE
              value: '100mb'
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  labels:
    app: mongo-express
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: mongo-express