apiVersion: v1    
kind: Secret
metadata:
  name: orgmanager-secrets
type: Opaque
data:
  mongoUrl: {{ .Values.options.mongoUrl | b64enc }}
  mongoExpressUserName: {{ .Values.mongoExpress.userName | b64enc }}
  mongoExpressPassword: {{ .Values.mongoExpress.password | b64enc }}

{{- if .Values.ldap.enabled }}
  ldapPassword: {{ .Values.ldap.password | b64enc }}
{{- end}}