apiVersion: v1    
kind: Secret
metadata:
  name: orgmanager-secrets
type: Opaque
data:
  mongoUrl: {{ .Values.options.mongoUrl | quote }}
  mongoExpressUserName: {{ .Values.mongoExpress.userName | quote }}
  mongoExpressPassword: {{ .Values.mongoExpress.password | quote }}