{{- if .Values.storage.filesystem.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "storage"
spec:
  storageClassName: microk8s-hostpath
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.filesystem.storage | quote }}
{{- end }}