extraEnvs:
  - name: SERVER_BASEPATH
    value: /util/kibana
  - name: SERVER_REWRITEBASEPATH
    value: 'true'

imageTag: "7.10.2"
image: "docker.elastic.co/kibana/kibana-oss"

resources:
  requests:
    cpu: "100m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

healthCheckPath: "/util/kibana/api/status"
elasticsearchHosts: "http://elasticsearch-logging.kube-system.svc.cluster.local:9200"