replicas: 1
discovery:
  type: single-node

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

# Disable privileged init Container creation.
sysctlInitContainer:
  enabled: false

# Restrict the use of the memory-mapping when sysctlInitContainer is disabled.
esConfig:
  elasticsearch.yml: |
    node.store.allow_mmap: false

# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "soft"

# Shrink default JVM heap.
esJavaOpts: "-Xmx128m -Xms128m"