extraEnvs:
  - name: SERVER_BASEPATH
    value: /util/kibana
  - name: SERVER_REWRITEBASEPATH
    value: 'true'

resources:
  requests:
    cpu: "100m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

healthCheckPath: "/util/kibana/app/kibana"
elasticsearchHosts: "http://elasticsearch-logging.kube-system.svc.cluster.local:9200"