label:
  name: gp-orgmanager

tag: edge

options:
  mutateData: true
  debugEnabled: false
  mongoUrl: mongodb://dbuser:qE6dP3mK1jX4rB5aH4cY6uP7lF3vV8pN@mongodb.mongodb.svc.cluster.local/orgmanager?authSource=orgmanager
  mongoDb: orgmanager

smtp:
  enabled: false
  ssl: ""

backup:
  mongodb:
    enabled: true
    schedule: "0 3,11,15,19 * * *"

sentry:
  enabled: true
  env: test
  rate: 1