label:
  name: gp-orgmanager

tag: edge

options:
  mutateData: true
  debugEnabled: false

smtp:
  enabled: false
  ssl: ""

backup:
  mongodb:
    enabled: true
    schedule: "0 3,11,15,19 * * *"

sentry:
  enabled: true
  env: test
  rate: 1