label:
  name: gp-orgmanager

tag: edge

storage:
  filesystem:
    enabled: true
    mount: /var/storage/
    storage: 30Gi

options:
  mutateData: true
  debugEnabled: false
  mongoUrl: mongodb://dbuser:qE6dP3mK1jX4rB5aH4cY6uP7lF3vV8pN@mongodb.mongodb.svc.cluster.local/orgmanager?authSource=orgmanager
  mongoDb: orgmanager

saml:
  enabled: true
  createUser: false

smtp:
  enabled: false
  ssl: ""
  sendToRecipient: false

backup:
  mongodb:
    enabled: true
    schedule: "0 3,11,15,19 * * *"

sentry:
  enabled: true
  env: test
  rate: 1

misc: 
  aspnetSecretsClaim: aspnetkeys2

mongoExpress:
  userName: admin15
  password: qE6dP3mK1jX4rB5aH4cY6uP7lF3vV8pN